# Generated by Django 4.1.1 on 2022-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='Имя')),
                ('userpassword', models.CharField(max_length=250, verbose_name='Пароль')),
                ('lastip', models.CharField(editable=False, max_length=15)),
                ('widgets_json', models.TextField(editable=False)),
                ('attached_boards', models.TextField(editable=False)),
                ('current_board', models.TextField(editable=False)),
                ('tasks', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
